### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by Crocodile29292** [lemonwaysas/LW4EC-Prestashop#1]
@sirateck 
Des clients qui ont une configuration de server qui bloque le flux quand on clique sur le bouton de paiement.
Il faut ajouter 
`header('Access-Control-Allow-Origin : *');`
au début du fichier `ajax.php`

**Comment by sirateck** [comment]
@Crocodile29292 
Pas de soucis. 
Par contre la méthode de sélection des cartes va changer dans la prochaine release.

**Comment by Crocodile29292** [comment]
Super. Merci 👍
