### ISSUE TITLE
Wording dans Prestashop: Remplacer "Lemon Way for E-commerce"

### ISSUE THREAD

**Issue by Crocodile29292** [lemonwaysas/LW4EC-Prestashop#2]
@sirateck 
Dans le mail de confirmation de commande ainsi que dans le mail de paiement accepté et dans la facture PDF que Prestashop réalise automatique à chaque commande, il est indiqué comme mode de paiement « Lemon Way for E-commerce » ce qui ne veut rien dire pour le client.
C'est mieux d'ajouter un champs dans la configuration pour que le webmaster puisse changer comme il veut.

**Comment by sirateck** [comment]
@Crocodile29292 
Cela est déjà développé dans la prochaine release.
L'admin pourra choisir un titre pour chaque type de méthode de paiement.

**Comment by Crocodile29292** [comment]
Merci 👍
